apiVersion: batch/v1
kind: Job
metadata:
  name: job-ml
spec:
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: ko3a4ok/ml-job:latest
        name: job-ml
