apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ko3a4ok/serving:latest
        command: ['streamlit','run', 'web/web.py', '--server.address=0.0.0.0']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ko3a4ok/serving:latest
        command: ['uvicorn', 'api.api:app', '--host=0.0.0.0']
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 8501
    protocol: TCP
  selector:
    app: web

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: api
