program: training.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: "uniform"
    min: 0.0001
    max: 0.1
  optimizer:
    values: ["adam", "sgd"]
  validation_split:
    max: 0.4
    min: 0.1
    distribution: uniform
  batch_size:
    max: 32
    min: 8
    distribution: int_uniform
  epochs:
    max: 16
    min: 1
    distribution: int_uniform
