apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "roma-model"
spec:
  predictor:
    containers:
      - name: kserve-container
        image: ko3a4ok/roma-model:latest
