name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: jobs
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-job:latest

  build-web:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: web
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-web:latest

  k8s-test-deployment-action:
    runs-on: ubuntu-latest
    steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy application
      run: |
        kubectl create -f k8s/deployment.yaml

    - name: Print pods
      run: |
        sleep 5 && kubectl get pod -A

    - name: Print pods
      run: |
        kubectl wait --for=condition=available --timeout=90s deployment/deployments-web

    - name: Print pods
      run: |
        sleep 5 && kubectl get pod -A

  k8s-test-job-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install and configure KinD
      run: |
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.20.0
        sudo mv $(go env GOPATH)/bin/kind /usr/local/bin/
        kind create cluster

    - name: Set up kubectl
      run: |
        kubectl cluster-info
        kubectl config use-context kind-kind

    - name: Deploy application
      run: |
        kubectl create -f k8s/job.yaml

    - name: Print pods
      run: |
        sleep 5 && kubectl get pod -A

    - name: Run tests
      run: |
        kubectl wait --for=condition=complete --timeout=90s job/job-ml

    - name: Print pods
      run: |
        sleep 5 && kubectl get pod -A

    - name: Clean up
      run: |
        kind delete cluster
